# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


user1 = User.create(name: "Grant")
user2 = User.create(name: "Brittney")
user3 = User.create(name: "Heidi")
user4 = User.create(name: "Yinning")

word1 = Word.create(word: "precipitate", correct_letter: "i", partial_word: "precip_tate")
word2 = Word.create(word: "serendipity", correct_letter: "e", partial_word: "ser_ndipity")
word3 = Word.create(word: "apotheosis" , correct_letter: "e", partial_word: "apoth_osis")
word4 = Word.create(word: "fleece", correct_letter: "e", partial_word: "fl_ece")
word5 = Word.create(word: "avarice", correct_letter: "a", partial_word: "av_rice")
word6 = Word.create(word: "pittance", correct_letter: "a", partial_word: "pitt_nce")
word7 = Word.create(word: "prevaricate", correct_letter: "a", partial_word: "prev_ricate")
word8 = Word.create(word: "sanctimonious", correct_letter: "i", partial_word: "sanct_monious")
word9 = Word.create(word: "desecrate", correct_letter: "e", partial_word: "des_crate")
word10 = Word.create(word: "reprobate", correct_letter: "o", partial_word: "repr_bate")
word11 = Word.create(word: "supercilious", correct_letter: "i", partial_word: "superc_lious")
word12 = Word.create(word: "quixotic", correct_letter: "u", partial_word: "q_ixotic")
word13 = Word.create(word: "malapropism", correct_letter: "a", partial_word: "mal_propism")
word14 = Word.create(word: "jaundice", correct_letter: "u", partial_word: "ja_ndice")
word15 = Word.create(word: "mercurial", correct_letter: "e", partial_word: "m_rcurial")
word16 = Word.create(word: "chauvinist", correct_letter: "i", partial_word: "chauv_nist")
word17 = Word.create(word: "zeitgeist", correct_letter: "i", partial_word: "ze_tgeist")
word18 = Word.create(word: "schadenfreude", correct_letter: "e", partial_word: "schad_nfreude")
word19 = Word.create(word: "indigent", correct_letter: "e", partial_word: "indig_nt")
word20 = Word.create(word: "scintillating", correct_letter: "i", partial_word: "scint_llating")
word21= Word.create(word:"extant" , correct_letter:"a" , partial_word:"ext_nt")
word22= Word.create(word:"anomaly", correct_letter:"a" , partial_word:"anom_ly")
word23= Word.create(word:"caliber" , correct_letter:"e" , partial_word:"calib_r")
word24= Word.create(word:"candor" , correct_letter:"o" , partial_word:"cand_r")
word25= Word.create(word:"aggregate" , correct_letter:"e" , partial_word:"aggr_gate")
word26= Word.create(word:"adumbrate", correct_letter:"u" , partial_word:"ad_mbrate")
word27= Word.create(word:"acquiescence" , correct_letter:"e" , partial_word:"acquiesc_nse")
word28= Word.create(word:"accolade" , correct_letter:"o" , partial_word:"acc_lade")
word29= Word.create(word: "abdicate", correct_letter:"i" , partial_word:"abd_cate")
word30= Word.create(word:"aberration" , correct_letter: "e", partial_word:"ab_rration")
word31= Word.create(word:"quarantine" , correct_letter:"a" , partial_word:"quar_ntine")
word32= Word.create(word:"perseverance" , correct_letter:"a" , partial_word:"persever_nce")
word33= Word.create(word:"secretary", correct_letter:"e" , partial_word:"secr_tary")
word34= Word.create(word:"repetition" , correct_letter:"e" , partial_word:"rep_tition")
word35= Word.create(word:"restaurant" , correct_letter:"u" , partial_word:"resta_rant")
word36= Word.create(word:"receipt" , correct_letter:"e" , partial_word:"rec_ipt")
word37= Word.create(word:"tomatoes" , correct_letter:"o" , partial_word:"tomat_es")
word38= Word.create(word:"upholstery" , correct_letter:"e" , partial_word:"upholst_ry")
word39= Word.create(word:"reference" , correct_letter:"e" , partial_word:"refer_nce")
word40= Word.create(word:"relevant" , correct_letter:"a" , partial_word:"relev_nt")
word41= Word.create(word:"presence" , correct_letter:"e" , partial_word:"pres_nce")
word42= Word.create(word:"parliament" , correct_letter:"i" , partial_word:"parl_ament")
word43= Word.create(word:"minuscule" , correct_letter:"u" , partial_word:"min_scule")
word44= Word.create(word:"memento" , correct_letter:"e" , partial_word:"m_mento")
word45= Word.create(word:"medieval" , correct_letter:"i" , partial_word:"med_eval")
word46= Word.create(word:"indispensable" , correct_letter:"a" , partial_word:"indispens_ble")
word47= Word.create(word:"guidance" , correct_letter:"a" , partial_word:"guid_nce")
word48= Word.create(word:"existence" , correct_letter:"e" , partial_word:"exist_nce")
word49= Word.create(word:"controversy" , correct_letter:"o" , partial_word:"contr_versy")
word50= Word.create(word:"daiquiri" , correct_letter:"i" , partial_word:"da_quiri")
word51= Word.create(word:"desperate" , correct_letter:"e" , partial_word:"desp_rate")
word52= Word.create(word:"colleague" , correct_letter:"a" , partial_word:"colle_gue")
word53= Word.create(word:"allegiance" , correct_letter:"a" , partial_word:"alligi_nce")
word54= Word.create(word:"advisable" , correct_letter:"a" , partial_word:"advis_ble")
word55= Word.create(word:"buoy" , correct_letter:"u" , partial_word:"b_oy")
word56= Word.create(word: "believe", correct_letter:"i" , partial_word:"bel_eve")
word57= Word.create(word: "adultery", correct_letter: "e", partial_word:"adult_ry")
word58= Word.create(word:"acreage" , correct_letter:"e" , partial_word:"acr_age")
word59= Word.create(word:"atheist" , correct_letter:"e" , partial_word:"ath_ist")
word60= Word.create(word:"argument" , correct_letter:"u" , partial_word:"arg_ment")
word61= Word.create(word:"amateur" , correct_letter:"u" , partial_word:"amate_r")
word62= Word.create(word:"mathematics" , correct_letter:"e" , partial_word:"math_matics")
word63= Word.create(word:"parallel" , correct_letter:"a" , partial_word:"par_llel")
word64= Word.create(word:"arithmetic" , correct_letter:"i" , partial_word:"ar_thmetic")
word65= Word.create(word:"nuisance" , correct_letter:"a" , partial_word:"nuis_nce")
word66= Word.create(word:"cemetery", correct_letter:"e" , partial_word:"cem_tery")
word67= Word.create(word:"calendar" , correct_letter:"a" , partial_word:"calend_r")
word68= Word.create(word:"breathe" , correct_letter:"e" , partial_word:"breath_")
word69= Word.create(word:"reverence" , correct_letter:"e" , partial_word:"rever_nce")
word70= Word.create(word:"changeable" , correct_letter:"a" , partial_word:"change_ble")
word71= Word.create(word:"noticeable" , correct_letter:"e" , partial_word:"notic_able")
word72= Word.create(word:"resemble" , correct_letter:"e" , partial_word:"res_mble")
word73= Word.create(word:"relieve" , correct_letter:"i" , partial_word:"rel_eve")
word74= Word.create(word:"acquaintance" , correct_letter:"a" , partial_word:"acquaint_nce")
word75= Word.create(word:"judgment" , correct_letter:"e" , partial_word:"judgm_nt")
word76= Word.create(word:"miscellaneous" , correct_letter:"e" , partial_word:"misc_llaneous")
word77= Word.create(word:"mischief" , correct_letter: "i", partial_word:"misch_ef")
word78= Word.create(word:"apartheid" , correct_letter:"e" , partial_word:"aparth_id")
word79= Word.create(word:"separate" , correct_letter:"a", partial_word:"sep_rate")
word80= Word.create(word:"maintenance" , correct_letter:"e" , partial_word:"maint_nance")




score1 = Score.create(score: 5, user_id: 1)
score2 = Score.create(score: 8, user_id: 2)
score3 = Score.create(score: 2, user_id: 3)
score4 = Score.create(score: 5, user_id: 4)
score5 = Score.create(score: 9, user_id: 1)